version: '3.8'
services:
  backend:
    image: recipe-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_ENV_VAR=value
    depends_on:
      - db
  db:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=mysecretpassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data