services:
  backend:
    image: hmchefapp-backend
    build:
      context: backend
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - "8001:8001"
    env_file:
      - backend/.env
    environment:
      - REDIS_URL=redis://default:verysecretpassword@redis:6379
    depends_on:
      - redis
    networks:
      - hmchefapp-network
  redis:
    image: redis/redis-stack-server:7.2.0-v14
    environment:
      - REDIS_PASSWORD=verysecretpassword
    ports:
      - "6379:6379"
    networks:
      - hmchefapp-network
  
networks:
  hmchefapp-network: