name: Lint & Build Android

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'assets/**'
      - 'constants/**'
      - 'context/**'
      - '.github/workflows/deploy.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'app.json'
      - 'prettier.config.js'
  workflow_dispatch:

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: ESLint Check
        run: npm run lint

      - name: Prettier Check
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: TypeScript Check
        run: npx tsc --noEmit
        continue-on-error: true 

  build:
    name: Build Android Release
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install dependencies
        run: npm ci && npm install -g eas-cli
      
      - name: Prebuild project
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk