name: Lint & Build Android

on:
  push:
    branches: [ main ]
    paths:
      - 'hmchefapp/app/**'
      - 'hmchefapp/assets/**'
      - 'hmchefapp/constants/**'
      - 'hmchefapp/context/**'
      - 'hmchefapp/.github/workflows/deploy.yml'
      - 'hmchefapp/package.json'
      - 'hmchefapp/package-lock.json'
      - 'hmchefapp/app.json'
      - 'hmchefapp/prettier.config.js'
  workflow_dispatch:

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: hmchefapp
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd hmchefapp && npm ci

      - name: ESLint Check
        run: cd hmchefapp && npm run lint

      - name: Prettier Check
        run: cd hmchefapp && npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: TypeScript Check
        run: cd hmchefapp && npx tsc --noEmit
        continue-on-error: true 

  build:
    name: Build Android Release
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: hmchefapp
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install dependencies
        run: cd hmchefapp && npm ci && npm install -g eas-cli
      
      - name: Prebuild project
        run: cd hmchefapp && eas build --platform android --profile preview --local --output ${{ github.workspace }}/hmchefapp.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hmchefapp
          path: ${{ github.workspace }}/hmchefapp.apk